### ISSUE TITLE
 volume dials are not mirrored with TotalMix and don't properly update

### ISSUE THREAD

**Issue by shells-dw** [shells-dw/loupedeck-totalmix#4]
Maybe my amateur description helps: 

when I change the status, e.g. "Dim Main" on the Loupedeck, the status in TotalMix and on the device itself changes instantly. 

If I change via Totalmix the change on the RME device (and TM of course) is instant, but it takes 2-3 sec. for the status on the Loupedeck to change. Solid Dim button gfx comes up. This behaviour is true for button status. 

But for all numeric dial status on the Loupedeck: the display only updates when I do changes on the Loupedeck device itself again, e.g. turn another dial, or switch App-Profile back and forth. After that "manual" update, all is in sync or value correct

_Originally posted by @LQdbMusic in https://github.com/shells-dw/loupedeck-totalmix/discussions/2#discussioncomment-4442747_

**Comment by shells-dw** [comment]
I've created an issue out of that, it's rather a specific issue than part of a discussion where it's buried within other conversations.

Alright. I've made a version specifically targeted at MacOS (there is no Windows package in there, I saved the time to build this version for Win, as it's not relevant here - in case anyone finds this thread and wants to play along and wonders why it wouldn't install 😉 ).

[TotalMix_1_6_2-debug.lplug4.zip](https://github.com/shells-dw/loupedeck-totalmix/files/10256502/TotalMix_1_6_2-debug.lplug4.zip)

Unzip the file (had to zip it to be able to upload it here), then install the loupedeck plugin file inside as usual.
After you've installed it, open `~/.local/share/Loupedeck/PluginData/TotalMix` in Finder and set `enableLogging` to `true` in `settings.json` - then save the file and restart Loupedeck (or well, stop then start again).

I've put logging off by default as this enables logging and traces for the whole Loupedeck - which tremendously slows down Loupedeck and all installed plugins with it. Hence making sure you can disable it at any time and also it's not messing things up right after install.

After Loupedeck started (again, this will take longer than usual, this is normal as long as logging and tracing are on), move faders in TotalMix that are present as dials on the Loupedeck and in view (make sure you move a fader for the actual channel you've put on Loupedeck, or it won't catch it). Would be nice to check 1 Input, 1 Output and 1 Playback channel, but either of each will do.
Don't worry that everything appears to be reacting super slow.
Don't close/exit Loupedeck yet, or the log file will be deleted.
Open `~/.local/share/Loupedeck/Logs` in Finder and attach the latest logfile you find here. It will be named something like `2022-12-19T07-37-53-9793_Loupedeck.log` and will probably have a size of 1-2MB.

It's the log for all the Loupedeck and all installed plugins (that happen to write in there). This shouldn't contain anything sensitive, but if you're worried, I'm only interested in lines containg the string "TotalMix:" - how you extract them is up to you though 😜 grep or sed should do that easily 😜 

You can continue to use this version for now, it's basically the same just with additional logging - just make sure to set `enableLogging` to `false` again.

**Comment by LQdbMusic** [comment]
Ok installed the debug version and here is the log file "grep"ed on Totalmix:

[TotalMix_debug_20221219.log.zip](https://github.com/shells-dw/loupedeck-totalmix/files/10259333/TotalMix_debug_20221219.log.zip)


PS. i noticed that TotalMix, which used to be VERY stable, is now crashing while the OSC-Server is running after 20-30 mins. Never happened to me with the Midi-Server enabled, maybe this something on my M1 with OSC only ?

**Comment by shells-dw** [comment]
Thanks budddy!
Found and eliminated the bug. When rewriting something a couple of versions back I put a "just for testing" value in and never made it properly... 🤷‍♂️ oh well. The log was really helpful in pointing me in the right direction.

I've had that crash myself once (just assuming it actually is that bug), but it was during debugging with breakpoints, thought it was caused by that. I'll try to track it down before pushing a new version. It sucks that a crashing plugin kills the whole Loupedeck (Streamdecks just restart the plugin but remain unaffected otherwise) so I'll rather have that fixed.
I'll keep you posted

**Comment by LQdbMusic** [comment]
Cool, happy to help, glad you found it and my logfile helped. Looking forward to the next version 👍🏻🥳

**Comment by shells-dw** [comment]
Just published [v1.7.0](https://github.com/shells-dw/loupedeck-totalmix/releases/tag/v1.7.0) which should eliminate the crashes that occured randomly (and some other bugs additionally)

Check it out and let me know if it works for you.

Cheers und frohe Weihnachten 😃

**Comment by LQdbMusic** [comment]
Just made a quick test, now all rotary knobs seems to work properly,
Overall update seems to be quicker as well 👍🏻 nice 👌🏻

**Comment by shells-dw** [comment]
thanks buddy, let me know if you encounter any further issues, closing that one now.
Frohes Fest
